version: "3.8"

services:
  takeover_scanner:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./domains.txt:/app/domains.txt
      - ./takeover_output:/app/takeover_output
    command: ["-f", "/app/domains.txt"]
