version: "3.8"

services:
  takeover_scanner:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./domains.txt:/app/domains.txt
      - ./output:/app/output
    command: ["-f", "/app/domains.txt"]
